---
abstract: 'Adds a Time::Moment object as a helper.'
author:
  - 'Scott Kiehn <sk.keenlinks@gmail.com>'
build_requires:
  Test::More: '1.302075'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.047, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-TimeMoment
provides:
  Mojolicious::Plugin::TimeMoment:
    file: lib/Mojolicious/Plugin/TimeMoment.pm
    version: '1.00'
requires:
  Mojolicious: '6.20'
  Scalar::Util: '0'
  Time::Moment: '0.44'
  Time::y2038: '20100403'
  perl: '5.008001'
version: '1.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
